name: Superset Frontend Build and Deploy

on:
  push:
    branches:
      - user-journey
  pull_request:
    branches:
      - user-journey

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        working-directory: superset-frontend
        run: npm ci

      - name: Build
        working-directory: superset-frontend
        run: npm run build

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH keys
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: -----BEGIN OPENSSH PRIVATE KEY---------END OPENSSH PRIVATE KEY-----

      - name: Deploy Superset to server
        run: |
          rsync -avz --delete --exclude '.git' --exclude '.github' --exclude '.gitignore' --exclude '.gitattributes' --update superset-frontend/ aziz@superset:/home/aziz/
