name: Superset Frontend Build and Deploy

on:
  push:
    branches:
      - user-journey
  pull_request:
    branches:
      - user-journey

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        working-directory: superset-frontend
        run: npm ci

      - name: Build
        working-directory: superset-frontend
        run: npm run build

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH keys
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: -----BEGIN OPENSSH PRIVATE KEY-----
            b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAACFwAAAAdzc2gtcnNhAAAAAwEAAQAAAgEA6mwAywJuVW2NFDgmCsZ6h4CFALB2Cv86VKaVAE7K3StvZQXu/IP2wbcULW+QJZs5kn3EZSK5ujtsvinnllZ9TaKl3t5iTmKBa7a8WSgAGNTRLiOCovEYWtS/Agyk8LmQaOc7Fy9Sk0opeljdAmtNVwstfR8SMMfFVG4ls6gkvaVikFacJV14HKYJ03+vT2Eo2GUL8LFa5uuD2TW8fM3ePoQuIF0V1rhxgMv3OuVrO5O20d63tjdLsZPd9qviWJMmuvBeks6zB8s7z0qQR/M25xsYAKCEMzMqH6ABAqPAg2VZOCTZuKTJ9H3N4+9wfCP6MTyMtnTrk0/TUJPZlMFjBrwkHhRFKEfC4ktZVPvi/GEluP2z8ooR6EjsmPXG7862+1PO8cnRczqNEtISaP8MKSmFmHAB4Cepx2cc54FTGx0xLSlf1xSA+rYz0nLYZ6atMZKpdNKtgGnuUavb/gXVkK6mRIhxy4NHzP8DMOJ5wTwoGNs6pwOTUQXKZ1H4Cvab6d/CdGD9MIyLa+OD3d1rcCR/2/Y7ZPsQpmyD1eCOy2WAh4hU8/xAHRicmo0BGctM7RBxhQ0ZZHT8nJFMtKVBTRV+a8d++rNJIeBO77hAtGFKNsD1GMOn40uiyJo2MY0ogvhap3mhm5n2Nn4jT+AcXrWR7yYbgotGKp2e6JS9GrMAAAdIWunDHFrpwxwAAAAHc3NoLXJzYQAAAgEA6mwAywJuVW2NFDgmCsZ6h4CFALB2Cv86VKaVAE7K3StvZQXu/IP2wbcULW+QJZs5kn3EZSK5ujtsvinnllZ9TaKl3t5iTmKBa7a8WSgAGNTRLiOCovEYWtS/Agyk8LmQaOc7Fy9Sk0opeljdAmtNVwstfR8SMMfFVG4ls6gkvaVikFacJV14HKYJ03+vT2Eo2GUL8LFa5uuD2TW8fM3ePoQuIF0V1rhxgMv3OuVrO5O20d63tjdLsZPd9qviWJMmuvBeks6zB8s7z0qQR/M25xsYAKCEMzMqH6ABAqPAg2VZOCTZuKTJ9H3N4+9wfCP6MTyMtnTrk0/TUJPZlMFjBrwkHhRFKEfC4ktZVPvi/GEluP2z8ooR6EjsmPXG7862+1PO8cnRczqNEtISaP8MKSmFmHAB4Cepx2cc54FTGx0xLSlf1xSA+rYz0nLYZ6atMZKpdNKtgGnuUavb/gXVkK6mRIhxy4NHzP8DMOJ5wTwoGNs6pwOTUQXKZ1H4Cvab6d/CdGD9MIyLa+OD3d1rcCR/2/Y7ZPsQpmyD1eCOy2WAh4hU8/xAHRicmo0BGctM7RBxhQ0ZZHT8nJFMtKVBTRV+a8d++rNJIeBO77hAtGFKNsD1GMOn40uiyJo2MY0ogvhap3mhm5n2Nn4jT+AcXrWR7yYbgotGKp2e6JS9GrMAAAADAQABAAACADnF31Yo5bdBFgVXJyz9qGHvrxex5Y2lRCNroIogYQer9jqgATuTbENmkt71wUE7Za9wNnA0ZDB9B7pACpa2/w+cl6N7DCBET6ATu4x/erKj9F+aGc59e6KbDu363sWC/g+UeTAoFgI9w0YnU2SOvFNI6m+NMkb6XOwHb1w9Ar0IXueyqK3ewMTSuNY6gCKgj9fw40Xw97W0clycTTU26WBf5BxOxJyT/UkgO3B07P4UU/iaGo2aSBneFtR9nP12WpO0vKIStfWkRTu7pR5OVwgS2dIBvUL/B5EetlEHuWDIn/nhvxSt7CXIwW686mx102nCAe3Pl+VIxYv0vClYlcYw1RgdJBYS5Us919QeasPuZhGcYFXIJ40XwIlK2lYfCOdRwgvJZT97kVhhMhd9OH/M8J8XWcaskXCyao0CLeR+KnsWkKN3My5Oz+MOT0rDkEwKQOaMJ6/d5YHpRWW9hVCdHpeC/jk2KSt5whSyyJyCgdYQe4st68V6hUWTf8JCiKdfIxMuWQZi20tAhS1vA7HEK/Q6IaZRepHa4lIfWTnh7TqajA/thzyumwyiO5ube1qx31qrAM/Yu3r8C1P2xP+W88iPi4Xqx9UTzz2nrq6NupXNKt/LuW2wkY/8oJoDHx6uoO+25MtP04ZjloWl+CLV0sv931gGcmf8xJ373wilAAABAQCKKWQmHNXJzi/orL3YusuY/c5PYE4WRs5d0TXjsW1XWj3QweisTp6466REB2BqeWifsZzQjwtvyYa93Q/YMZEhtEe0dJddfS0c8VxcZtluN7oAXZE34hlukeWYiRHQRkRe04r9GX3Bji5/klOemVUouVTgAQH1LPOUj4t/hN5Bgc6kEYuuMlVJDh4ksIRfkszArmctsxyTpgrOvlsOtPFTWxiqdgwsRzfmie/cQpKp8QUw7p8f3m7GhWasyiDbmW5ZXDSdnp7gRjDkKbNldY1l7e9KijSyf6uCXBnYCI4ps+JwcEbnohWlAyPXBgizeEKb2WPPgSUVnKKKn3Z1Ti0sAAABAQDtKP26V8j7T6Fi2n9MppSNV/TtDLUqvkKxamcPg3uPkXdRDMxzhfEafHreejYVFDgHh9iHFpn7+NwQ34Vh8sohbHMMB/OTGgf+TXOoSQCmHCFsij6wZz5+yHV5E4mkVZAxzBKnn6B7cxk21fXh1f/jT5hkuyomSW6k7ABqqisjNz2RLQ2VhdSSl0JOT+pvYnQkLvjF3mkIE/bhx7GquEz4e9An76yNaeMhtWar6NuPHokA/R/XiuBj3qOVV5QpPohJ5bBIhgX93c9ylgyTGOsOwp95EgxcfTze3f16kWQuiedy01Y1PwfDfNDxp98vq3oHANR/1HOPvaGfri2KTkHHAAABAQD9C1NqfsKbSjEw2WbZnNCsB0Ts/+7ydtZxxJLc9SHSOboETk5Vdlg6ma4sJ8nO450zUweXb8t+p9tawMnLEnNspurOCuWv+Y1FY5g8dcmnh1x9P/fuE7ImiBfUS/gaWU1cYWiPIHKWPom3pvlzChwBuJxSbgbIdmyVx529bmsD3yGNWaJmTwyaEyGnI2NyM5u5F0I9Uo5EA3zrAzJQZZVRkpCQSpyoE4G+Sp4Tw1h1FUIM/0WPJhE5vkBhOcPM6tZr01JJdDKS8xpDHNJUX/qDl0Qatju+wfRuKNZXo99vWuBANwpDHe+ni5CwwZKFYVLnJBllCro4che5xKfrAp+1AAAADWF6aXpAc3VwZXJzZXQBAgMEBQ==
            -----END OPENSSH PRIVATE KEY-----

      - name: Deploy Superset to server
        run: |
          rsync -avz --delete --exclude '.git' --exclude '.github' --exclude '.gitignore' --exclude '.gitattributes' --update superset-frontend/ aziz@superset:/home/aziz/
