name: Superset Frontend Build

on:
  push:
    branches:
      - user-journey
  pull_request:
    branches:
      - user-journey

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        working-directory: superset-frontend
        run: npm ci

      - name: Build Superset frontend
        working-directory: superset-frontend
        run: npm run build

      - name: Remove existing build directory
        run: rm -rf build

      - name: Create build directory
        run: mkdir build

      - name: Move build files
        run: |
          shopt -s nullglob
          cp -R build/. build/

      - name: Archive build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: superset-frontend
          path: ./build
