name: Superset Frontend Build

on:
  push:
    branches:
      - user-journey
  pull_request:
    branches:
      - user-journey

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        working-directory: superset-frontend
        run: npm ci

      - name: Remove existing build directory
        run: rm -rf superset-frontend/build

      - name: Create build directory
        run: mkdir superset-frontend/build

      - name: Build Superset frontend
        working-directory: superset-frontend
        run: npm run build

      - name: Archive build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: superset-frontend
          path: superset-frontend/build

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: superset-frontend
          path: ${{ github.workspace }}/superset-frontend/build

      - name: Move build artifacts to repository
        run: mv ${{ github.workspace }}/superset-frontend/build superset-frontend/build
